name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # testing job configuration and steps
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the python versions that need to be tested on
        python-version: ["3.9", "3.10", "3.11"]

#    # Service containers to run with job - uncomment to allow database connected tests
#    services:
#      # Label used to access the service container
#      postgres:
#        # Docker Hub image
#        image: postgres
#        # Provide the password for postgres
#        env:
#          POSTGRES_PASSWORD: postgres
#        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          # Maps tcp port 5432 on service container to the host
#          - 5432:5432

    steps:

      - name: 1. Checkout the code...
        uses: actions/checkout@v3

      - name: 2. Configure Python version ${{ matrix.python-version }}...
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: 3. Install dependencies...
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: 4. Run the tests...
        run: |
          python -m pytest .


  # linting job configuration and steps
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # only need to lint the latest version
        python-version: ["3.11"]

    steps:
      - name: 1. Checkout the code...
        uses: actions/checkout@v3

      - name: 2. Configure Python version ${{ matrix.python-version }}...
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: 3. Run the linters...
        uses: pre-commit/action@v3.0.0
